### ISSUE TITLE
Prepare the first release

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#60]
Edit: the list is getting longer. Maybe each one should be converted to an issue and this should become the pull request.
https://developer.chrome.com/webstore/publish
- [x] rename `public/images/default.png` to `public/images/128.png` and resize it to 128x128 (need to rename all code occurrences) #72 #76
- [x] add a promotional image of size 440x280 #72
- [x] add `screenshot.png` of size 1280x800 #90
- [x] add `detailed_description.txt` for each locale #89
- [x] delete numerous `console.log();`s #96
- update version to `1.0.0` in `manifest.json`

**Comment by Bartleby2718** [comment]
Also, `tile icon` seems to be a better name than `promo` because that's the word Google uses.: https://developer.chrome.com/webstore/publish#provide-store-content
